services:
  - type: web
    name: insect-control-spray-team
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run db:deploy && npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: LINE_LOGIN_CHANNEL_ID
        sync: false
      - key: LINE_LOGIN_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_TARGET_USER_ID
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
